//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoEntities : DbContext
    {
        public proyectoEntities()
            : base("name=proyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_cantidad_cuotas> tb_cantidad_cuotas { get; set; }
        public virtual DbSet<tb_credenciales> tb_credenciales { get; set; }
        public virtual DbSet<tb_cuotas> tb_cuotas { get; set; }
        public virtual DbSet<tb_estados_maritales> tb_estados_maritales { get; set; }
        public virtual DbSet<tb_generos> tb_generos { get; set; }
        public virtual DbSet<tb_intereses> tb_intereses { get; set; }
        public virtual DbSet<tb_pagos> tb_pagos { get; set; }
        public virtual DbSet<tb_prestamos> tb_prestamos { get; set; }
        public virtual DbSet<tb_roles> tb_roles { get; set; }
        public virtual DbSet<tb_tipo_clientes> tb_tipo_clientes { get; set; }
        public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }
        public virtual DbSet<tb_bitacora_prestamos> tb_bitacora_prestamos { get; set; }
    }
}
