//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_intereses
    {
        public int id_interes { get; set; }
        public decimal porcentaje_interes { get; set; }
        public int id_tipo_cliente { get; set; }
        public int id_cantidad_cuota { get; set; }
    
        public virtual tb_cantidad_cuotas tb_cantidad_cuotas { get; set; }
        public virtual tb_tipo_clientes tb_tipo_clientes { get; set; }
    }
}
