//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuarios()
        {
            this.tb_prestamos = new HashSet<tb_prestamos>();
            this.tb_prestamos1 = new HashSet<tb_prestamos>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int edad { get; set; }
        public string dpi { get; set; }
        public int id_estado_marital { get; set; }
        public int id_tipo_cliente { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime fecha_actualizacion { get; set; }
        public long id_genero { get; set; }
        public int id_credencial { get; set; }
    
        public virtual tb_credenciales tb_credenciales { get; set; }
        public virtual tb_estados_maritales tb_estados_maritales { get; set; }
        public virtual tb_generos tb_generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_prestamos> tb_prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_prestamos> tb_prestamos1 { get; set; }
        public virtual tb_tipo_clientes tb_tipo_clientes { get; set; }
    }
}
